FROM almalinux:10

# System dependencies
RUN dnf groupinstall -y "Development Tools" && \
    dnf install -y openssl openssl-devel && \
    dnf clean all && \
    rm -rf /var/cache/dnf

ARG files_fbthrift_cachebust=1
COPY files_fbthrift/ /
CMD ["/build-fbthrift.sh"]
