#!/bin/sh

PROJECT=$(cd "$(dirname "$0")/.." && pwd)
cd "$PROJECT"

if [ -x /usr/bin/podman ]; then
	DOCKER=/usr/bin/podman
elif [ -x /usr/bin/docker ]; then
	DOCKER=/usr/bin/docker
else
	echo "No podman or docker binary found!" >&2
	exit 1
fi
