name: fbthrift
on:
  workflow_dispatch:
  schedule:
    - cron: "10 17 3 * *"

permissions:
  contents: read

jobs:
  fbthrift-el10:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-26.04
            arch: amd64
          - os: ubuntu-26.04-arm
            arch: arm64

    steps:
      - uses: actions/checkout@v5

      - name: Build fbthrift tarball
        run: ./scripts/fbthrift-build.sh

      - name: Try fbthrift tarball on el10
        run: ./scripts/fbthrift-smoketest.sh

      - name: Try fbthrift tarball on fc44
        run: ./scripts/fbthrift-smoketest.sh -d fc44

      - name: Try fbthrift tarball on ub2604
        run: ./scripts/fbthrift-smoketest.sh -d ub2604

      - name: Get artifact name
        id: artifact_name
        run: |
          set -e

          name="$(basename "$(find ./artifacts -name '*.tar.xz' | head -n1)")"
          name="${name%.tar.xz}"
          echo "name=$name" >>"$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact_name.outputs.name }}
          path: artifacts/fbthrift-*.tar.xz
