name: sapling
on:
  workflow_dispatch:
  schedule:
    - cron: "18 22 * * *"

permissions:
  contents: read

jobs:
  sapling-el10:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-26.04
            arch: amd64
          - os: ubuntu-26.04-arm
            arch: arm64

    steps:
      - uses: actions/checkout@v5

      # - name: Fetch fbthrift
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: ./scripts/fbthrift-fetch.sh

      - name: Build sapling RPM and run tests
        run: ./scripts/sapling-build.sh -t

      - name: Try sapling RPM
        run: ./scripts/sapling-smoketest.sh

      - name: Get artifact name
        id: artifact_name
        run: |
          set -e

          name="$(basename "$(find ./artifacts -name '*.rpm' | head -n1)")"
          name="${name%.rpm}"
          echo "name=$name" >>"$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.artifact_name.outputs.name }}
          path: artifacts/sapling-*.rpm
